# Generated by Django 5.1.15 on 2026-02-23 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "nickname",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(50),
                        ],
                    ),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("status", models.IntegerField(choices=[(0, "active"), (1, "suspended"), (2, "withdrawn")], default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status"], name="idx_members_status")],
            },
        ),
    ]
