# Generated by Django 5.1.15 on 2026-02-23 21:49

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("status", models.IntegerField(choices=[(0, "draft"), (1, "published"), (2, "archived")], default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status"], name="idx_posts_status")],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("title"),
                        models.F("user_id"),
                        name="unique_post_title_per_user",
                    )
                ],
            },
        ),
    ]
