# Generated by Django 5.1.15 on 2026-03-03 03:30

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(200)])),
                ('content', models.TextField(blank=True, default='')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'published'), (2, 'archived')], default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='idx_posts_status')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('member'), name='unique_post_title_per_member')],
            },
        ),
    ]
